---
title: "A Bayesian framework for distributed lag non-linear models: the {bdlnm} R package"
author: 
 - name: "**Pau<br>Satorra**"
   affiliations: 
    - name: "Biostatistics Support and Research Unit, IGTP" 
 - name: "**Marcos Quijal-Zamorano**"
   affiliations: 
    - name: "Institute of Social and Preventive Medicine (ISPM), University of Bern" 
 - name: "**Joan Ballester**"
   affiliations: 
    - name: "Institut de Salut Global de Barcelona (ISGlobal)" 
 - name: "**Miguel Ángel Martínez-Beneito**"
   affiliations: 
    - name: "Departament d'Estadística i Investigació Operativa, Universitat de València"
 - name: "**Marc Marí-Dell'Olmo**"
   affiliations: 
    - name: "Agència de Salut Pública de Barcelona (ASPB)"
date: "2026-05-26"
date-format: long
bibliography: references.bib
format: 
  revealjs:
    smaller: true
    slide-number: true
    controls: true
    progress: true
    theme: [default, WWW/bdlnm-theme.scss]
---

```{r setup, echo = FALSE, include = FALSE}
library(bdlnm)

# DLNMs and splines
library(dlnm)
library(splines)

# Data manipulation
library(dplyr)
library(reshape2)
library(stringr)
library(lubridate)

# Visualization
library(ggplot2)
library(gganimate)
library(ggnewscale)
library(patchwork)
library(scales)
library(plotly)

# Tables
library(gt)

# Execution time
library(tictoc)
```

```{r echo = FALSE}
# Exposure-response and lag-response spline parameters
dlnm_var <- list(
  var_prc = c(10, 75, 90),
  var_fun = "ns",
  lag_fun = "ns",
  max_lag = 21,
  lagnk = 3
)

# Build cross-basis 
argvar <- list(
  fun = dlnm_var$var_fun,
  knots = quantile(london$tmean, dlnm_var$var_prc / 100, na.rm = TRUE),
  Bound = range(london$tmean, na.rm = TRUE)
)
arglag <- list(
  fun = dlnm_var$lag_fun,
  knots = logknots(dlnm_var$max_lag, nk = dlnm_var$lagnk)
)

cb <- crossbasis(london$tmean, lag = dlnm_var$max_lag, argvar, arglag)
```

```{r echo = FALSE}
seas <- ns(london$date, df = round(8 * length(london$date) / 365.25))
```

```{r echo = FALSE}
temp <- round(seq(min(london$tmean), max(london$tmean), by = 0.1), 1)
```

```{r echo = FALSE}
mod <- bdlnm(
  mort_75plus ~ cb + factor(dow) + seas,
  data = london,
  family = "poisson",
  sample.arg = list(n = 1000, seed = 5243)
)
```

```{r echo = FALSE}
mmt <- optimal_exposure(mod, exp_at = temp)
```

```{r echo = FALSE}
cen <- mmt$summary[["0.5quant"]]
cpred <- bcrosspred(mod, exp_at = temp, cen = cen)
```

```{r echo = FALSE}
matRRfit <- cbind(
  melt(cpred$matRRfit.summary[,, "0.5quant"], value.name = "RR"),
  RR_lci = melt(
    cpred$matRRfit.summary[,, "0.025quant"],
    value.name = "RR_lci"
  )$RR_lci,
  RR_uci = melt(
    cpred$matRRfit.summary[,, "0.975quant"],
    value.name = "RR_uci"
  )$RR_uci
) |>
  rename(temperature = Var1, lag = Var2) |>
  mutate(
    lag = as.numeric(gsub("lag", "", lag))
  )

temps <- cpred$exp_at
```

## Exposure-lag-response surface

```{=html}
<iframe 
  src="www/exposure_lag_surface.html"
  width="100%"
  height="650"
  style="border: none;">
</iframe>
```

## References